export const actions = {
  ADD_CART_REQUEST: "ADD_CART_REQUEST",
  ADD_CART_SUCCESS: "ADD_CART_SUCCESS",
  ADD_CART_FAILURE: "ADD_CART_FAILURE",
  FETCH_CART_REQUEST: "FETCH_CART_REQUEST",
  FETCH_CART_SUCCESS: "FETCH_CART_SUCCESS",
  FETCH_CART_FAILURE: "FETCH_CART_FAILURE",
  REMOVE_CART_REQUEST: "REMOVE_CART_REQUEST",
  REMOVE_CART_SUCCESS: "REMOVE_CART_SUCCESS",
  REMOVE_CART_FAILURE: "REMOVE_CART_FAILURE",
  EMPTY_CART_REQUEST: "EMPTY_CART_REQUEST",
  EMPTY_CART_SUCCESS: "EMPTY_CART_SUCCESS",
  EMPTY_CART_FAILURE: "EMPTY_CART_FAILURE",
};
